buildscript {
    repositories {
        maven { name = "forge"; url = "https://maven.minecraftforge.net" }
        maven { name = "sonatype"; url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        mavenCentral()
        jcenter()
        maven {
            name = "spongepowered"
            url = "https://repo.spongepowered.org/maven"
        }
        maven {
            name = "cleanroom"
            url = "https://repo.cleanroommc.com/releases"
        }
        maven {
            name = "blamejared"
            url = "https://maven.blamejared.com"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT"
    classpath "org.spongepowered:mixingradle:0.6-SNAPSHOT"
    }
}

apply plugin: "net.minecraftforge.gradle.forge"
apply plugin: "org.spongepowered.mixin"

version = "0.1.0"
group = "net.coderbot"
archivesBaseName = "oculus"

sourceCompatibility = targetCompatibility = "1.8"

def relictiumVersion = "1.2.0"

minecraft {
    version = "1.12.2-14.23.5.2768"
    runDir = "run"
    mappings = "stable_39"
    makeObfSourceJar = false
}

repositories {
    maven {
        name = "ForgeMaven"
        url = "https://maven.minecraftforge.net"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "CleanroomMC"
        url = "https://repo.cleanroommc.com/releases"
    }
    maven {
        name = "Rongmario"
        url = "https://maven.rongmario.com"
    }
}

sourceSets {
    main {
        ext.refMap = "oculus.refmap.json"
    }
}

dependencies {
    deobfCompile "maven.modrinth:relictium:${relictiumVersion}"
    compile "org.spongepowered:mixin:0.8.5"
    compile "zone.rong:mixinbooter:8.0"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
}

mixin {
    defaultObfuscationEnv "searge"
    add sourceSets.main, "oculus.mixins.json"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include "**/*"
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

def generatedRefmap = file("${buildDir}/tmp/compileJava/compileJava-refmap.json")

tasks.register("copyRefmap", Copy) {
    dependsOn compileJava
    from(generatedRefmap)
    into("${buildDir}/resources/main")
    rename { "oculus.refmap.json" }
    onlyIf { generatedRefmap.exists() }
}

tasks.getByName("classes") {
    dependsOn "copyRefmap"
}
